# Generated by Django 5.2.7 on 2025-11-03 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('FITA', 'Fita'), ('LINHA', 'Linha'), ('ENFEITE', 'Enfeite'), ('PRESILHA', 'Presilha'), ('ARCO', 'Arco'), ('OUTROS', 'Outros')], max_length=100)),
                ('cor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompraMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(choices=[('QUANTIDADE', 'Quantidade'), ('CM', 'Centímetro')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_por_quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_por_cm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True)),
                ('data_compra', models.DateField(default=django.utils.timezone.now)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='app.materiaprima')),
            ],
        ),
    ]
