# Generated by Django 5.2.7 on 2025-11-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compramateriaprima',
            name='marca',
            field=models.CharField(blank=True, default='Genérico', max_length=100, null=True),
        ),
    ]
