# Generated by Django 5.2.7 on 2025-11-04 19:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_compramateriaprima_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('LACO', 'Laço'), ('TIARA', 'Tiara'), ('FAIXA', 'Faixa')], max_length=10)),
                ('custo_fixo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_material_usado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materiaprima')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_usados', to='app.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produto', models.PositiveIntegerField(default=0)),
                ('valor_produto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('materia_prima_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
            ],
        ),
    ]
