# Generated by Django 5.2.7 on 2025-11-04 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_produto_materialusado_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialusado',
            name='materia_prima',
        ),
        migrations.AddField(
            model_name='materialusado',
            name='compra_materia_prima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.compramateriaprima'),
        ),
    ]
