# Generated by Django 5.2.7 on 2025-11-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_materialusado_materia_prima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cola', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('isqueiro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('das_mei', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxas_bancarias', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tempo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='lucro_por_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_em_estoque',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
