# Generated by Django 5.2.7 on 2025-11-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_custofixo_produto_lucro_por_venda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custofixo',
            name='tempo',
        ),
    ]
