# Generated by Django 5.2.7 on 2025-11-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_custofixo_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialusado',
            name='tipo_unidade',
            field=models.CharField(choices=[('QUANTIDADE', 'Quantidade'), ('CM', 'Centímetro')], default='CM', max_length=20),
        ),
    ]
