# Generated by Django 5.2.7 on 2025-11-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_despesa_venda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Despesa',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
