# Generated by Django 5.2.7 on 2025-11-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_despesa_delete_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='compramateriaprima',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
