# Generated by Django 5.2.7 on 2025-11-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_compramateriaprima_ativo_materiaprima_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compramateriaprima',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='ativo',
        ),
    ]
