# Generated by Django 5.2.7 on 2025-11-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_despesa_venda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Despesa',
        ),
    ]
