# Generated by Django 5.2.7 on 2025-11-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_custofixo_embalagem_custofixo_etiqueta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custofixo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='custofixo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
