# Generated by Django 5.2.7 on 2025-11-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_custofixo_updated_at_alter_custofixo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custofixo',
            name='updated_at',
        ),
    ]
