# Generated by Django 5.2.7 on 2025-11-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_itemvenda_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='compramateriaprima',
            name='quantidade_restante_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='compramateriaprima',
            name='quantidade_restante_un',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
