# Generated by Django 5.2.7 on 2025-11-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_compramateriaprima_quantidade_restante_cm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compramateriaprima',
            name='quantidade_restante_cm',
        ),
        migrations.RemoveField(
            model_name='compramateriaprima',
            name='quantidade_restante_un',
        ),
    ]
