# Generated by Django 5.2.7 on 2025-11-29 15:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_compramateriaprima_quantidade_restante_cm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustoFixoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(help_text='Primeiro dia do mês ao qual este custo fixo se refere (Ex: 2025-01-01)', unique=True)),
                ('energia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cola', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('isqueiro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('das_mei', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxas_bancarias', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('papeleta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('embalagem', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('etiqueta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('outros_variaveis', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Custo Mensal (Variável e Fixo)',
                'verbose_name_plural': 'Custos Mensais (Variáveis e Fixos)',
            },
        ),
        migrations.CreateModel(
            name='MetasFinanceiras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(help_text='Primeiro dia do mês ao qual a meta se refere (Ex: 2025-01-01)', unique=True)),
                ('meta_faturamento_mensal', models.DecimalField(decimal_places=2, default=Decimal('6750.00'), help_text='Meta mensal de faturamento (Limite MEI é R$ 6.750,00)', max_digits=10)),
                ('meta_lucro_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('meta_quantidade_vendas', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='custo_unitario_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Custo do produto no momento da venda (para relatórios)', max_digits=10),
        ),
    ]
