# Generated by Django 5.2.7 on 2025-11-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_custofixomensal_metasfinanceiras_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetasFinanceiras',
        ),
    ]
